# Generated by Django 3.0.4 on 2020-03-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200326_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal',
            new_name='Feeding',
        ),
    ]
